apiVersion: core.api.humanitec.io/v1
kind: Definition
metadata:
  id: temp-creds-route53
object:
  name: temp-creds-route53
  driver_type: humanitec/dns-aws-route53
  org_id: humanitec-nick
  type: dns
  driver_account: test-aws-assumerole
  driver_inputs:
    values:
      domain: newapp.io
      hosted_zone_id: Z1TT32KTKHMF93
      template: ${context.app.id}-${context.env.id}
