apiVersion: core.api.humanitec.io/v1
kind: Definition
metadata:
  id: iam-policy-s3-tf-admin
object:
  type: aws-policy
  driver_type: humanitec/terraform
  driver_inputs:
    values:
      source:
        url: https://github.com/humanitec-hackteam5/terraform-demo
        rev: refs/heads/main
        path: iam-policy-s3-admin
      variables:
        s3_bucket_arn: "${resources['s3.default'].outputs.arn}"
        region: "${resources['s3.default'].outputs.region}"
        s3_bucket: "${resources['s3.default'].outputs.bucket}"
    secrets:
      variables:
        credentials:
          access_key: ${resources['base-env.default'].outputs.aws.access_key}
          secret_key: ${resources['base-env.default'].outputs.aws.secret_key}
  criteria:
    - class: s3-admin
