apiVersion: core.api.humanitec.io/v1
kind: Definition
metadata:
  id: s3-tf-public
object:
  type: s3
  driver_type: humanitec/terraform
  driver_inputs:
    values:
      source:
        url: https://github.com/humanitec-hackteam5/terraform-demo
        rev: refs/heads/main
        path: s3-public
      variables:
        bucket: ${context.app.id}.${context.env.id}.public
        region: eu-west-3
    secrets:
      variables:
        credentials:
          access_key: ${resources['base-env.default#base-env'].outputs.aws.access_key}
          secret_key: ${resources['base-env.default#base-env'].outputs.aws.secret_key}
  provision:
    aws-policy:
      is_dependant: false
      match_dependants: true
  criteria:
    - class: external
